CREATE TABLE IF NOT EXISTS Carts (
    cart_id varchar(128),
    user_name varchar(64),
    active boolean
);

CREATE TABLE IF NOT EXISTS Positions (
    id int primary key GENERATED BY DEFAULT AS IDENTITY,
    product_id varchar(128),
    cart_id varchar(128) references Carts(cart_id),
    quantity int
);